drone:
  image: drone
  ports:
  - 80:8000
  environment:
    - PLUGIN_FILTER=plugins/* slingshot/*
    - REMOTE_DRIVER=gitlab
    - HTTP_PROXY=http://10.201.100.158:8888
    - ENV_GIN_MODE=release
    - REMOTE_CONFIG=http://git.prod.skyscanner.local?client_id=0e93b9ebbe628accd0e046a01217d24737801cf9aa736eefb83a005406a2cea1&client_secret=28188bfeea4ebab0ba235911aacc25ed2563a2459f86938a5ce1b8c963c1c7e4
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/drone:/var/lib/drone
  privileged: true


